const sections = [
  ["overview","Overview"],["skills","Skills"],["research","Research Inbox"],["assembly","Assembly"],
  ["approvals","Approvals"],["routing","Routing Simulator"],["automation","Automation"],
  ["updates","Updates & Rollback"],["memory","Context Memory"],["diagnostics","Diagnostics"]
];
const params = new URLSearchParams(location.search);
const token = params.get("token") || sessionStorage.getItem("agent-os-token") || "";
if (token) sessionStorage.setItem("agent-os-token", token);
history.replaceState({}, "", location.pathname);
const headers = () => ({"Authorization":`Bearer ${token}`,"Content-Type":"application/json"});
async function api(path, options={}) { const response=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}}); const data=await response.json(); if(!response.ok) throw new Error(data.error?.message || data.reason_codes?.join(", ") || `HTTP ${response.status}`); return data; }
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function showSection(id){ document.querySelectorAll(".panel").forEach(x=>x.classList.toggle("active",x.id===id)); document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.target===id)); }
function setupNav(){ const nav=document.querySelector("#nav"); sections.forEach(([id,label],i)=>{const b=document.createElement("button");b.textContent=label;b.dataset.target=id;b.className=i===0?"active":"";b.onclick=()=>showSection(id);nav.appendChild(b);}); }
function card(title,value,state="neutral"){return `<article class="card"><h3>${esc(title)}</h3><div class="status ${state}">${esc(value)}</div></article>`;}
async function loadOverview(){ const d=await api("/api/overview"); document.querySelector("#health").textContent=d.doctor.state;document.querySelector("#health").className=`status ${d.doctor.state==="BOUND"?"good":"bad"}`;document.querySelector("#overview-content").innerHTML=[card("Doctor",d.doctor.state,d.doctor.state==="BOUND"?"good":"bad"),card("Release",d.release.release_id,"good"),card("Core entries",d.release.entries,"neutral"),card("Git",`${d.git.branch} · ${d.git.dirty?"dirty":"clean"}`,d.git.dirty?"warn":"good"),card("Remote",d.git.remotes.length?"configured":"not configured",d.git.remotes.length?"good":"warn"),card("Connectors",d.connectors.map(x=>`${x.id}: ${x.status}`).join(" · "),"neutral")].join("");document.querySelector("#updates-content").textContent=`Release ${d.release.release_id}; source ${d.release.source_commit}. Capability integration creates a working-baseline manifest; verified release still requires the separate content and manifest commits.`;document.querySelector("#diagnostics-content").textContent=JSON.stringify(d,null,2);}
async function loadSkills(){ const d=await api("/api/skills");const target=document.querySelector("#skill-list");target.innerHTML=d.capabilities.map(x=>`<article class="card"><div class="row"><span class="pill ${x.lifecycle_state==="active"?"good":"warn"}">${esc(x.lifecycle_state)}</span><span class="pill">${esc(x.integration_mode)}</span><span class="pill">${esc(x.project_override)}</span></div><h3>${esc(x.id)}</h3><p>${esc(x.summary)}</p><p><b>Use:</b> ${esc(x.when_to_use[0])}</p><p><b>Risk:</b> ${esc(x.risk.level)} · <b>Eval:</b> ${esc(x.eval.status)} · <b>Usage:</b> ${esc(d.usage_counts[x.id]||0)}</p><button class="secondary" data-skill="${esc(x.id)}">Explain</button></article>`).join("");target.querySelectorAll("[data-skill]").forEach(b=>b.onclick=async()=>{const detail=await api(`/api/skills/${encodeURIComponent(b.dataset.skill)}`);const el=document.querySelector("#skill-detail");el.classList.remove("hidden");el.textContent=JSON.stringify(detail,null,2);});}
async function loadResearch(){ const d=await api("/api/research");document.querySelector("#research-content").innerHTML=`<div class="grid">${card("Candidates",d.candidates.length,"neutral")}${card("Decision receipts",d.decisions.length,"neutral")}${card("Registry",d.validation.ok?"valid":"invalid",d.validation.ok?"good":"bad")}</div><pre class="detail">${esc(JSON.stringify(d.status,null,2))}</pre>`;document.querySelector("#assembly-content").textContent=d.candidates.length?"Select a candidate from Research Inbox to compare.":"No candidate is in release authority. Discovery results remain outside active routing until approved.";}
function setupIntegration(){const form=document.querySelector("#integration-form");form.onsubmit=async e=>{e.preventDefault();let candidate,assembly;try{candidate=JSON.parse(form.candidate.value);assembly=JSON.parse(form.assembly.value);}catch(error){alert(`Invalid JSON: ${error.message}`);return;}const planned=await api("/api/skills/integrations/plan",{method:"POST",body:JSON.stringify({candidate,assembly})});const el=document.querySelector("#integration-plan");el.classList.remove("hidden");el.textContent=JSON.stringify(planned.plan,null,2);await loadApprovals();};}
async function loadLifecycle(){const d=await api("/api/lifecycle");document.querySelector("#lifecycle-content").textContent=JSON.stringify(d,null,2);}
async function loadMemory(){const healthTarget=document.querySelector("#memory-health"),detail=document.querySelector("#memory-content");try{const d=await api("/api/memory");healthTarget.innerHTML=[card("State",d.health.state,d.health.state==="FRESH"?"good":d.health.state==="STALE"?"warn":"bad"),card("Authoritative",d.context.authoritative?"yes":"no",d.context.authoritative?"good":"warn"),card("Hot records",d.context.records.length,"neutral"),card("Active tasks",d.context.tasks.length,"neutral"),card("Handoffs",d.handoff_count,"neutral")].join("");detail.textContent=JSON.stringify(d,null,2);}catch(error){healthTarget.innerHTML=card("Context Memory","unconfigured or degraded","warn");detail.textContent=error.message;}}
function setupMemory(){document.querySelector("#memory-initialize").onclick=async()=>{await api("/api/memory/initialize/plan",{method:"POST",body:JSON.stringify({})});await loadApprovals();};document.querySelector("#memory-refresh").onclick=async()=>{await api("/api/memory/refresh/plan",{method:"POST",body:JSON.stringify({})});await loadApprovals();};document.querySelector("#memory-plan").onclick=async()=>{const operation=document.querySelector("#memory-operation").value;let value;try{value=JSON.parse(document.querySelector("#memory-input").value);}catch(error){alert(`Invalid JSON: ${error.message}`);return;}const key={proposals:"proposal",tasks:"task",handoffs:"handoff",compactions:"compaction"}[operation];await api(`/api/memory/${operation}/plan`,{method:"POST",body:JSON.stringify({[key]:value})});await loadApprovals();};}
async function loadSettings(){ const d=await api("/api/settings");const s=d.project;const form=document.querySelector("#settings-form");form.innerHTML=`<div class="split"><label>Default mode<select name="default_mode"><option>FAST</option><option>STANDARD</option><option>DEEP</option></select></label><label>Discovery<select name="discovery"><option value="event-driven-and-manual">Event-driven + manual</option><option value="manual-only">Manual only</option><option value="disabled">Disabled</option></select></label><label>GitHub<select name="github"><option>optional</option><option>disabled</option></select></label><label>NotebookLM<select name="notebooklm"><option>optional</option><option>disabled</option></select></label><label>Max candidates<input name="max_candidates" type="number" min="1" max="100"></label><label>Plan expiry seconds<input name="expiry" type="number" min="60" max="3600"></label></div><label>Capability overrides JSON<textarea name="overrides" rows="6" placeholder='{"capability-id":"manual-only"}'></textarea></label><div class="callout">Allowed overrides: automatic · manual-only · disabled. Locked: activation approval ON · background daemon OFF · auto-commit OFF · auto-push OFF</div><p><button type="submit">Create settings plan</button></p>`;form.default_mode.value=s.default_mode;form.discovery.value=s.automation.discovery;form.github.value=s.connectors.github;form.notebooklm.value=s.connectors.notebooklm;form.max_candidates.value=s.budgets.max_candidates_per_scan;form.expiry.value=s.budgets.plan_expiry_seconds;form.overrides.value=JSON.stringify(s.capability_overrides||{},null,2);form.onsubmit=async e=>{e.preventDefault();let overrides;try{overrides=JSON.parse(form.overrides.value||"{}");}catch(error){alert(`Invalid overrides JSON: ${error.message}`);return;}const desired=structuredClone(s);desired.default_mode=form.default_mode.value;desired.automation.discovery=form.discovery.value;desired.connectors.github=form.github.value;desired.connectors.notebooklm=form.notebooklm.value;desired.budgets.max_candidates_per_scan=Number(form.max_candidates.value);desired.budgets.plan_expiry_seconds=Number(form.expiry.value);desired.capability_overrides=overrides;const planned=await api("/api/settings/plan",{method:"POST",body:JSON.stringify({desired})});const el=document.querySelector("#settings-plan");el.classList.remove("hidden");el.textContent=JSON.stringify(planned.plan,null,2);await loadApprovals();};}
async function loadApprovals(){const d=await api("/api/transactions");const target=document.querySelector("#approval-content");const pending=d.plans.filter(x=>x.status==="pending-approval");target.innerHTML=pending.length?`<table><thead><tr><th>Plan</th><th>Domain</th><th>Risk</th><th>Diff</th><th>Action</th></tr></thead><tbody>${pending.map(x=>`<tr><td>${esc(x.plan_id)}</td><td>${esc(x.transaction_domain)}</td><td>${esc(x.risk||x.operation)}</td><td><pre>${esc(x.exact_diff)}</pre></td><td><button data-apply="${esc(x.plan_id)}">Approve & Apply</button></td></tr>`).join("")}</tbody></table>`:`<div class="callout">No pending approval.</div>`;target.querySelectorAll("[data-apply]").forEach(b=>b.onclick=async()=>{if(!confirm(`Apply reviewed plan ${b.dataset.apply}?`))return;await api(`/api/transactions/${encodeURIComponent(b.dataset.apply)}/apply`,{method:"POST",body:JSON.stringify({confirm:true})});await Promise.all([loadApprovals(),loadSettings(),loadOverview(),loadSkills(),loadResearch(),loadLifecycle(),loadMemory()]);});}
function setupRouting(){document.querySelector("#routing-form").onsubmit=async e=>{e.preventDefault();const p=document.querySelector("#routing-prompt").value;const d=await api(`/api/routing?prompt=${encodeURIComponent(p)}`);document.querySelector("#routing-result").textContent=JSON.stringify(d,null,2);};}
async function start(){setupNav();setupRouting();setupIntegration();setupMemory();try{await Promise.all([loadOverview(),loadSkills(),loadResearch(),loadSettings(),loadApprovals(),loadLifecycle(),loadMemory()]);}catch(e){document.querySelector("#health").textContent="Unavailable";document.querySelector("#health").className="status bad";document.querySelector("#diagnostics-content").textContent=e.stack||e.message;showSection("diagnostics");}}
start();
